### PR TITLE
Add basic sets documentation

### PR DESCRIPTION
**Pull request by faucetlol**
Add some basic documentation for post sets, though I haven't figured out maintainers or _actually adding posts to the set_ yet.

### CODE REVIEW

**Comment by DonovanDMC** [comment]
Post maintainers can't be managed via json
https://github.com/e621ng/e621ng/blob/8d3c8f40c3f3b49402e74459d969b7a532c7cf55/app/controllers/post_set_maintainers_controller.rb

I'd recommend trying to comprehend the rails controllers for routes you have no idea about
https://github.com/e621ng/e621ng/blob/8d3c8f40c3f3b49402e74459d969b7a532c7cf55/app/controllers/post_sets_controller.rb

If you have rubymine, you'll probably have a lot better of a time as it'll show actual paths up above method names
image

Also, side note, I'd prefer most routes be referenced by their full name, e.g. "Post Sets"
The only one in which I'm planning on deviating from this currently is `/help`, which I'll be calling "Help Pages"

**Comment by faucetlol** [comment]
I guess the ability to manage maintainers via json went away when e621ng happened, because I've definitely done that in the past many years ago. 

I did use the controller as a reference but didn't realise those two methods had a path for them - thanks for the tip for rubymine, I'll check that out for sure. That will make it a _lot_ easier.

I was conflicted on whether I should name it "Sets" or "Post Sets" because the site UI exclusively refers to them as "Sets" - but considering it's an API reference I guess it'll be best to go with the path names. I'll make another commit soon with the names adjusted and some documentation for the add and remove posts methods.

**Comment by DonovanDMC** [comment]
Do note ruby mine is a paid application, if you have a jetbrains license it'll have it included
It also has a 30 day trial

I'm not sure if there are any other editors for ruby that will show paths for routes

**Comment by DonovanDMC** [comment]
The post set maintainers route responds to `.js` apparently, though not sure how useful that really is

**Comment by DonovanDMC** [comment]
The `Moderator+` color should be red to match janitor - I've just made that change so I'm sure I've missed a few places

I'm going with what's in the code for what I'm listing as possible order values
<https://github.com/e621ng/e621ng/blob/69fc143ec7b3df4321c6efa24ed622d26ba58935/app/models/post_set.rb#L330-L343>
(missing `update` and `postcount`, even though these are aliases)

I'm still making my way back across the docs as that's also a recent change

**Comment by faucetlol** [comment]
(finger slipped on the close button lol)
 
> I'm going of what's in the code for what I'm listing as possible order values https://github.com/e621ng/e621ng/blob/69fc143ec7b3df4321c6efa24ed622d26ba58935/app/models/post_set.rb#L330-L343 (missing `update` and `postcount`, even though these are aliases)
> 
> I'm still making my way back across the docs as that's also a recent change

Makes sense, how do you want me to format it? Just including them in the list like the others, or should I specifically make note of the fact they're just aliases?

**Comment by DonovanDMC** [comment]
Just include them next to the other values as if they were nothing different

**Comment by faucetlol** [comment]
GitBook was refusing to sync my changes for some reason so I ended up just manually editing the file 🙃

That should be everything discussed, I hope I didn't make any more mistakes.

**Comment by DonovanDMC** [comment]
I love that the preview url said "peace, I'm out"

**Comment by DonovanDMC** [comment]
Since the preview url vanished and gitbook refuses to sync this pr to another space, I'm just going to merge this and go from there

**Comment by faucetlol** [comment]
P a i n 🙃

**Pull request merged**
